### ISSUE TITLE
Please add JSON file support

### ISSUE THREAD

**Issue by ckissi** [cvbge/vscode-escape-string#1]
Can you add support for JSON file types, please?

**Comment by SzczurekYT** [comment]
Yes please.

**Comment by jlewin** [comment]
I forked this and for my purposes, this three line modification gave me the json support I was looking for:

```javascript
 } else if (languageId === "json") {
    const json = JSON.stringify(s);
    return json.substring(1, json.length -1);
``

**Comment by cvbge** [comment]
Thanks, merged your pull request!
